/**
 * Style: a photographic clinical operations record rooted in one permanent Kabezi site. All imagery
 * is Twese-supplied and the content describes current clinical work without service-volume claims.
 */
import { ArrowRight } from "lucide-react";
import { Link } from "wouter";
import SiteFrame, { LogoLockup } from "@/components/SiteFrame";

const services = ["General primary care", "Maternal health", "Child health", "Chronic disease management", "Mental health support", "Nutrition services"];

export default function Clinic() {
  return <SiteFrame>
    <section className="clinic-hero" style={{ backgroundImage: "url(/manus-storage/twese-clinic-kabezi-exterior-operations.jpg_fd1aebe3.webp)" }}><div className="container clinic-hero__content"><p className="eyebrow eyebrow--light">Twese Clinic</p><h1>Primary care built for Kabezi.</h1><p>Twese Clinic operates a permanent primary-care site in Kabezi, providing ongoing primary and preventive care within a rural catchment of more than 150,000 people.</p><p>The clinic is designed around continuity, affordability, local staffing, community follow-up, and the realities of practicing medicine where advanced diagnostics and specialist services are limited.</p></div></section>
    <section className="clinic-introduction"><div className="container clinic-introduction__grid"><div><LogoLockup division="clinic" /><p className="location-stamp">Kabezi, Bujumbura Province, Burundi</p><p className="lead">Twese Clinic provides primary and preventive care from one permanent site in Kabezi. Its clinical model combines direct care, chronic-disease management, community-health follow-up, and practical systems for maintaining continuity outside the clinic.</p><p>The objective is not to replicate a large hospital. It is to build a reliable primary-care system capable of managing as much disease locally as possible.</p></div><figure className="document-photo"><img src="/manus-storage/EvelynCenter_e3bf89c3.webp" alt="Interior of the Twese Clinic care setting in Kabezi" /></figure></div></section>
    <section className="clinic-services"><div className="container"><div className="clinic-services__heading"><div><p className="page-kicker">Clinical services</p><h2>Clinical services</h2></div><p>These categories describe the clinic’s current primary-care scope rather than patient-volume targets.</p></div><div className="clinic-services__grid">{services.map((service, index) => <article key={service}><span>{String(index + 1).padStart(2, "0")}</span><h3>{service}</h3></article>)}</div></div></section>
    <section className="clinic-community"><div className="container clinic-community__grid"><figure className="document-photo"><img src="/manus-storage/clinic-community-medication_56272d0c.jpg" alt="A Twese Clinic clinician preparing medication during a care encounter" /></figure><div><p className="page-kicker">Community health</p><h2>Care continues between visits.</h2><p>Approximately <strong>14 Community Health Workers</strong> extend clinical follow-up beyond the Kabezi site.</p><p>Their work supports blood-pressure monitoring, chronic-disease follow-up, health education, treatment continuity, and communication between the clinic and surrounding communities.</p></div></div></section>
    <section className="clinic-development"><div className="container clinic-development__grid"><div><p className="page-kicker">Local capacity</p><h2>Building more capability closer to patients.</h2><p>Advanced imaging, specialist services, and higher-level clinical infrastructure remain limited outside major urban centers.</p><p>Twese’s response is therefore not simply to refer more patients elsewhere. The organization is working to strengthen what can be diagnosed, monitored, and treated locally — while developing new technical capacity through Twese Labs where existing infrastructure does not meet the need.</p></div><figure className="document-photo"><img src="/manus-storage/clinic-equipment-detail_5a5a3e5a.jpg" alt="Diagnostic supplies prepared in the Twese Clinic care setting" /></figure></div></section>
    <section className="clinic-focus"><div className="container clinic-focus__grid"><div><p className="page-kicker">Current focus</p><h2>Kabezi site operations</h2><p>Current work focuses on care delivery, chronic disease management, clinical follow-up, data systems, and day-to-day site operations.</p></div><div className="clinic-focus__photos"><figure className="document-photo"><img src="/manus-storage/clinic-community-waiting_e945d468.jpg" alt="Community members gathered near Twese Clinic in Kabezi" /></figure><figure className="document-photo"><img src="/manus-storage/windowhall_a8a03d85.webp" alt="A window and interior detail at the Twese Clinic site" /></figure></div></div></section>
    <section className="clinic-end"><div className="container clinic-end__grid"><div><p className="page-kicker">Related work</p><h2>Care and research, documented together.</h2></div><Link href="/labs" className="button button--navy">Explore Twese Labs <ArrowRight size={16} /></Link></div></section>
  </SiteFrame>;
}
