/**
 * Style: evidence-led institutional record using verified operating context, clinical work, and field-response
 * documentation. It presents one permanent Kabezi site without charts, projections, or donor-oriented language.
 */
import { ArrowRight, MapPin } from "lucide-react";
import { Link } from "wouter";
import SiteFrame, { PageHero } from "@/components/SiteFrame";

const services = ["General primary care", "Maternal health", "Child health", "Chronic disease management", "Mental health support", "Nutrition services"];
const systemOfCare = [["Clinical care", "Primary, preventive, maternal, child, and chronic-disease care are delivered from the permanent Kabezi site."], ["Community follow-up", "Fourteen Community Health Workers extend care beyond the clinic, supporting follow-up, chronic-disease monitoring, health education, and continuity between visits."], ["Building capability locally", "Specialist services, advanced diagnostics, transportation, and higher-level facilities remain limited in much of rural Burundi. Twese therefore focuses on building as much clinical and technical capability locally as possible."]];

export default function Impact() {
  return <SiteFrame>
    <PageHero eyebrow="Impact" title="A rural health system built around Kabezi." intro="Twese Clinic operates a permanent primary-care site in Kabezi, Bujumbura Province, within a rural catchment of more than 150,000 people. Care is organized around primary and preventive medicine, maternal and child health, chronic disease management, community follow-up, and the practical systems required to deliver care in a resource-constrained setting." marker="" />
    <section className="impact-facts"><div className="container"><p className="page-kicker">Core operating record</p><div className="impact-facts__grid"><article><strong>150,000+</strong><p>Rural catchment population</p></article><article><strong>$0</strong><p>Cost to patients at point of care</p></article><article><strong>14</strong><p>Community Health Workers</p></article><article><strong>Since 2023</strong><p>Permanent clinical operations in Kabezi</p></article></div></div></section>
    <section className="routine-care"><div className="container routine-care__grid"><figure className="document-photo"><img src="/manus-storage/impact-routine-care-bp_a7cf33ca.jpg" alt="A Twese Clinic clinician conducting a blood-pressure assessment during a routine care visit" /></figure><div><p className="page-kicker">Clinical work</p><h2>Core clinical work.</h2><p>Twese Clinic provides primary and preventive care from its Kabezi site, with services organized around the clinical needs most consistently encountered in the surrounding community.</p><ul>{services.map(service => <li key={service}>{service}</li>)}</ul></div></div></section>
    <section className="impact-priorities"><div className="container impact-priorities__grid"><div><p className="page-kicker">System of care</p><h2>One care system, from the clinic into the community.</h2><p>Twese is organized around continuity rather than isolated clinical encounters.</p></div><ol>{systemOfCare.map(([title, copy], index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></div></section>
    <section className="conflict-story" style={{ backgroundImage: "url(/manus-storage/impact-conflict-response_d165d66c.jpg)" }}><div className="container conflict-story__content"><p className="eyebrow eyebrow--light">Field response</p><h2>Temporary care during regional displacement</h2><p>During a period of regional displacement, Twese extended temporary clinical services to more than <strong>1,500 displaced women and children.</strong> This was a time-limited extension of the Kabezi clinical system rather than a separate permanent Twese site.</p></div></section>
    <section className="impact-geography"><div className="container impact-geography__grid"><figure className="document-photo impact-geography__image"><img src="/manus-storage/june11-01a_07f6ecb5.jpg" alt="Rural landscape in the Twese photographic record" /></figure><div className="impact-geography__content"><div className="impact-geography__icon" aria-hidden="true"><MapPin size={25} /></div><div><p className="page-kicker">Permanent clinical site</p><h2>Kabezi, Bujumbura Province, Burundi</h2><p>Twese Clinic’s permanent clinical operations are based in Kabezi within a rural catchment of more than 150,000 people. The clinic’s operating model is built around the clinical, economic, transportation, and infrastructure realities of this setting.</p></div></div></div></section>
    <section className="impact-end"><div className="container impact-end__grid"><div><p className="page-kicker">Collaboration</p><h2>Work with Twese</h2><p className="impact-end__copy">Clinical, research, engineering, and institutional collaborations are developed around defined operating and research priorities.</p></div><Link href="/partner" className="button button--navy">Partner With Us <ArrowRight size={16} /></Link></div></section>
  </SiteFrame>;
}
