/**
 * Style: a restrained biomedical-engineering and health-systems research record with sober technical figures,
 * qualified design goals, and no simulated laboratory evidence or completed-clinical-result claims.
 */
import { ArrowRight } from "lucide-react";
import { Link } from "wouter";
import SiteFrame from "@/components/SiteFrame";

const workstreams = [["Magnet architecture", "0.2 T permanent-magnet Halbach architecture using thermally stable SmCo components."], ["Field optimization", "Simulation, passive shimming, active shimming, and homogeneity improvement."], ["RF & gradients", "Development of RF and gradient subsystems appropriate for the target geometry and field strength."], ["Acquisition & reconstruction", "MaRCoS-based signal acquisition, sequence development, and image reconstruction."], ["Validation", "Phantom testing, field characterization, thermal evaluation, and iterative system validation."], ["Deployment engineering", "Housing, power, maintainability, installation requirements, and operation in low-infrastructure clinical environments."]];
const outputs = [["2026", "International Society for Magnetic Resonance in Medicine (ISMRM) — Cape Town, South Africa", "AccessMR low-field MRI research presented at the 2026 Annual Meeting."], ["2026", "Harvard Africa Healthcare Conference", "Second place, abstract competition."], ["2025", "American Medical Student Association (AMSA) — INNOFEST", "AccessMR selected as an honoree."], ["Manuscript", "Computational Design of a Thermally Stable Halbach Array Targeting 0.2 Tesla for Low-Field MRI Using Stock Magnets", "Status: Under review"], ["Manuscript", "Innovative Healthcare Financing in Africa: Investment-Backed Primary Care in Rural Burundi", "Status: In preparation"]];
const collaboration = [["Academic & clinical research", "Global health, imaging science, biomedical engineering, implementation science, health systems, and clinical research."], ["Engineering", "Magnet systems, RF, gradients, reconstruction, electronics, hardware, simulation, and infrastructure-aware system design."], ["Institutional research", "Hospitals, universities, investigators, laboratories, and research groups interested in responsible, ethics-reviewed clinical and technical collaboration."]];

function TechnicalVisual() { return <figure className="technical-visual" aria-label="Technical direction research figure"><p>Technical direction</p><div className="technical-visual__field"><span>0.2 T</span><small>Target field strength</small></div><figcaption>Configuration studies and technical inputs under evaluation</figcaption></figure>; }

export default function Labs() {
  return <SiteFrame>
    <section className="labs-hero"><div className="container labs-hero__grid"><div><p className="eyebrow eyebrow--light">Twese Labs</p><h1>Engineering medical technology around the realities of rural care.</h1><p>Twese Labs develops medical technology for settings where cost, power, climate, maintenance, supply chains, and specialist access determine whether a device can actually be deployed.</p><p>Research begins with constraints observed through clinical operations and converts them into engineering requirements.</p></div><TechnicalVisual /></div></section>
    <section className="labs-overview"><div className="container labs-overview__grid"><figure className="document-photo labs-overview__image"><img src="/manus-storage/home-labs-operational-technology_acf3e145.jpg" alt="Operational equipment in a Twese clinical setting" /></figure><div><p className="location-stamp">Clinical operations → observed constraint → engineering requirement</p><h2>Clinical constraints become engineering requirements.</h2><p>Twese Labs is grounded in the day-to-day realities observed through Twese Clinic.</p><p>Instead of adapting expensive hospital technology after the fact, the lab asks a different question:</p><p className="lead">What would this technology look like if it were designed from the beginning for a rural health system?</p><p>Work spans biomedical engineering, imaging science, clinical medicine, health systems research, and implementation.</p></div></div></section>
    <section className="accessmr-research"><div className="container accessmr-research__grid"><div><p className="page-kicker">Research initiative</p><h2>AccessMR</h2><p>AccessMR is Twese Labs’ low-field MRI program.</p><p>The project is developing a 0.2 Tesla imaging architecture designed around the infrastructure constraints that make conventional MRI difficult to deploy in low-resource settings.</p><p>Current engineering work includes magnet architecture, magnetic-field optimization and shimming, RF and gradient systems, signal acquisition through MaRCoS, reconstruction, phantom validation, enclosure design, power requirements, thermal stability, and maintainability.</p><p>The objective is not simply to build a cheaper MRI scanner. It is to determine whether a deliberately simplified imaging system can preserve clinically useful capability while substantially reducing the infrastructure required for MRI.</p></div><div className="accessmr-research__side"><div className="research-specs"><p>Technical direction</p><div><span>Target field strength</span><strong>0.2 Tesla</strong></div><div><span>System cost design target</span><strong>&lt; $15,000</strong></div><div><span>Infrastructure design objective</span><strong>Low-power architecture</strong></div><div><span>Thermal design context</span><strong>20–40°C operating environment</strong></div></div></div></div></section>
    <section className="labs-development"><div className="container labs-development__grid"><div><p className="page-kicker">Engineering workstreams</p><h2>Current technical work</h2></div><div className="labs-development__list">{workstreams.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
    <section className="labs-outputs"><div className="container"><div className="labs-outputs__heading"><p className="page-kicker">Research & recognition</p><h2>Research outputs</h2></div><div className="labs-outputs__list">{outputs.map(([year, title, detail]) => <article key={`${year}-${title}`}><p className="output-year">{year}</p><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div></div></section>
    <section className="labs-collaboration labs-collaboration--photo" style={{ backgroundImage: "url(/manus-storage/home-approach-community_6b89a08a.jpg)" }}><div className="container labs-collaboration__content"><p className="page-kicker">Research & engineering collaboration</p><div className="labs-collaboration__grid">{collaboration.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="labs-end"><div className="container labs-end__grid"><div><p className="page-kicker">Collaboration</p><h2>Collaborate on research and development.</h2></div><Link href="/partner" className="button button--navy">Partner With Us <ArrowRight size={16} /></Link></div></section>
  </SiteFrame>;
}
